### ISSUE TITLE
Error when following the install instructions 

### ISSUE THREAD

**Issue by FoleyDom** [gieart87/ci4-cicommerce#25]
This is the error receiving:

PHP Fatal error:  Uncaught Error: Undefined constant "CodeIgniter\CLI\ENVIRONMENT" in /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/CLI/CLI.php:666
Stack trace:
#0 /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/CLI/CLI.php(707): CodeIgniter\CLI\CLI::streamSupports('stream_isatty', Resource id #2)
#1 /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/CLI/CLI.php(159): CodeIgniter\CLI\CLI::hasColorSupport(Resource id #2)
#2 /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/CLI/CLI.php(1115): CodeIgniter\CLI\CLI::init()
#3 /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(312): include_once('/Users/dfoley/p...')
#4 /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile('/Users/dfoley/p...')
#5 /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace('CodeIgniter\\CLI...')
#6 /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/CLI/Console.php(49): CodeIgniter\Autoloader\Autoloader->loadClass('CodeIgniter\\CLI...')
#7 /Users/dfoley/ppp/ci4-cicommerce/spark(54): CodeIgniter\CLI\Console->showHeader()
#8 {main}
  thrown in /Users/dfoley/ppp/ci4-cicommerce/vendor/codeigniter4/framework/system/CLI/CLI.php on line 666

Any help on what I should do?

**Comment by bhaskar-c** [comment]
Exact same issue here when running the command:  php spark migrate -n IonAuth. What is supposed to be done ?
